/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import communication.Communication;
import domain.Pharmacist;
import domain.Receipt;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logic.DetailsType;
import logic.ViewEnum;
import session.MySession;

/**
 *
 * @author Andrija - PC
 */
public class MainForm extends javax.swing.JFrame {
Pharmacist logged;
    /**
     * Creates new form MainForm1
     */
    public MainForm() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        logged=(Pharmacist) MySession.getInstance().getValue("logged_pharmacist");
        lblPharmacist.setText(logged.toString());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        lblPharmacist = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemPatientNew = new javax.swing.JMenuItem();
        itemPatientView = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemMedicineNew = new javax.swing.JMenuItem();
        itemMedicineView = new javax.swing.JMenuItem();
        itemRecieptNew = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        itemView = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        viewStattitem = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLogout.setText("Log out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jMenu1.setText("Patients");

        itemPatientNew.setText("New");
        itemPatientNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPatientNewActionPerformed(evt);
            }
        });
        jMenu1.add(itemPatientNew);

        itemPatientView.setText("View");
        itemPatientView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPatientViewActionPerformed(evt);
            }
        });
        jMenu1.add(itemPatientView);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Medicine");

        itemMedicineNew.setText("New");
        itemMedicineNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMedicineNewActionPerformed(evt);
            }
        });
        jMenu2.add(itemMedicineNew);

        itemMedicineView.setText("View");
        itemMedicineView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMedicineViewActionPerformed(evt);
            }
        });
        jMenu2.add(itemMedicineView);

        jMenuBar1.add(jMenu2);

        itemRecieptNew.setText("Receipt");

        jMenuItem1.setText("New");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        itemRecieptNew.add(jMenuItem1);

        itemView.setText("View");
        itemView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemViewActionPerformed(evt);
            }
        });
        itemRecieptNew.add(itemView);

        jMenuBar1.add(itemRecieptNew);

        jMenu3.setText("Sale statistics");

        viewStattitem.setText("View");
        viewStattitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStattitemActionPerformed(evt);
            }
        });
        jMenu3.add(viewStattitem);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPharmacist)
                .addContainerGap(742, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblPharmacist)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 352, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemPatientViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPatientViewActionPerformed
        ViewForm form = new ViewForm(ViewEnum.PATIENT);
        form.setVisible(true);
        form.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        form.pack();
    }//GEN-LAST:event_itemPatientViewActionPerformed

    private void itemPatientNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPatientNewActionPerformed
        PatientDetailsForm form = new PatientDetailsForm(this, rootPaneCheckingEnabled, DetailsType.ADD);
        form.setVisible(true);
        form.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        form.pack();
    }//GEN-LAST:event_itemPatientNewActionPerformed

    private void itemMedicineNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMedicineNewActionPerformed
        MedicineDetailsForm form = new MedicineDetailsForm(this, rootPaneCheckingEnabled, DetailsType.ADD);
        form.setVisible(true);
        form.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        form.pack();
    }//GEN-LAST:event_itemMedicineNewActionPerformed

    private void itemMedicineViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMedicineViewActionPerformed
        ViewForm form = new ViewForm(ViewEnum.MEDICINE);
        form.setVisible(true);
        form.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        form.pack();
    }//GEN-LAST:event_itemMedicineViewActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ReceiptForm form = new ReceiptForm(this, rootPaneCheckingEnabled, new Receipt(), logged,DetailsType.ADD);
        form.setVisible(true);
        form.pack();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void itemViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemViewActionPerformed
        ViewForm form = new ViewForm(ViewEnum.RECEIPT);
        form.setVisible(true);
        form.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        form.pack();
    }//GEN-LAST:event_itemViewActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int x = JOptionPane.showConfirmDialog(this, "Are you sure?", "", WIDTH, JOptionPane.YES_NO_OPTION);
        if(x == JOptionPane.YES_OPTION) {
            try {
                Communication.getInstance().logout(logged);
                this.dispose();
                Communication.getInstance().connect();
                loginForm form = new loginForm();
                form.setVisible(true);
                form.pack();
            } catch (Exception ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
       }
        
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void viewStattitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStattitemActionPerformed
        ViewForm form = new ViewForm(ViewEnum.SALE_STATISTICS);
        form.setVisible(true);
        form.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        form.pack();
    }//GEN-LAST:event_viewStattitemActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JMenuItem itemMedicineNew;
    private javax.swing.JMenuItem itemMedicineView;
    private javax.swing.JMenuItem itemPatientNew;
    private javax.swing.JMenuItem itemPatientView;
    private javax.swing.JMenu itemRecieptNew;
    private javax.swing.JMenuItem itemView;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel lblPharmacist;
    private javax.swing.JMenuItem viewStattitem;
    // End of variables declaration//GEN-END:variables

}
